FROM node:18-alpine AS builder
# Install dependencies
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . . 

RUN npm run build

# runner stage - keep final image small

FROM node:18-alpine

WORKDIR /app

# copy only necessary files from builder stage
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/node_modules ./node_modules

# Expose port
EXPOSE 3000

# Start the application
CMD ["npx","next","start"]